# Generated by Django 3.2.4 on 2025-06-20 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20250620_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelogentry',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='changelog_entries', to='website.repository'),
        ),
    ]
