# Generated by Django 3.2.4 on 2025-06-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_changelogentry_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelogentry',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
